### ISSUE TITLE
请秦总把剩下的1660工资还给我吧

### ISSUE THREAD

**Issue by wuhaohao1234** [wind13/javaxunit#1]
原本想给你微信说来着，但是你一直不加我微信，仔细想想你占有公司25%的股份，现在提交个issues。请让秦总把剩下的工资还给我，马上快过年了

**Comment by wuhaohao1234** [comment]
公司都拖欠工资一年了，我给公司的秦总打电话，也不接

**Comment by wuhaohao1234** [comment]
要是还不发，我就给你github上所有的项目提交issues。你要是不理，我就提交pull request

**Comment by jdz321** [comment]
好家伙  github维权？都是人才

**Comment by wuhaohao1234** [comment]
只能在github维权了，微信被拉黑，给老板打电话不接

**Comment by wind13** [comment]
你要请别人帮忙，可以用更好的方式，这样好吗？

**Comment by wind13** [comment]
不加你微信是因为不想交你这样的朋友，做事不择手段，不顾颜面和方式，所以要远离。 你工资的事我不知情，你完全可以先通过别的方式告知我情况，我的电话至少是能打通的吧？做事不要太过份。

**Comment by wuhaohao1234** [comment]
工资给了就行，你电话我不知道

**Comment by wuhaohao1234** [comment]
给了我自然会关闭issues

**Comment by wuhaohao1234** [comment]
作为公司股东，公司财务情况怎么可能不知情
